### ISSUE TITLE
Invalid response if EPG data contains \r (0xD)

### ISSUE THREAD

**Issue by idl0r** [hampelratte/svdrp4j#2]
Hi,

parsing of EPG fails (enter e.g. the channel list) if the actual data contains \r (0xD) characters.
Example data (\r/0xD is displayed as ^M):
```
220 vdr SVDRP VideoDiskRecorder 2.2.0; Sat Sep 26 19:00:57 2015; UTF-8^M
215-C C-9999-161-12102 SAT.1
215-E 19115 1443286671 1749 4E 1C
215-T K 11 - Kommissare im Einsatz
215-S Geld und Liebe, Ermittler-Doku, D 2013
215-D Renate B. wird brutal aus ihrem Haus entführt. Am nächsten Tag bekommt der aufgelöste Ehemann ein Erpresserschreiben. Der Täter verlangt 100.000 Euro Lösegeld! Die Kommissare bereiten alles für eine Übergabe vor, doch plötzlich erhalten sie einen tragischen Anruf des Entführers: Die vermisste Frau ist tot! Doch wieso bringt der Verbrecher sein einziges Druckmittel um?^MDarsteller:^MMichael Mayer (Dr. Christian Alsleben)^MGerrit Grass^MMichael Naseband^MAlexandra Rietz^MJonas Rohrmann (Robert Ritter)
215-e
215-c
215 End of EPG data^M
```
Sorry for that bad example :P

In this case we'll start here:
https://github.com/hampelratte/svdrp4j/blob/master/src/main/java/org/hampelratte/svdrp/Connection.java#L277

So we'll parse the "215-D" line. in.readLine() will will split the line on any ^M (0xD aka \r) which results into a valid line and the next one(s) into invalid ones. Line 286 (the integer parsing) fails and the exception will be catched, resulting into a code=-1. As the fourth character of that broken string is NOT "-" it will be parsed and we'll break on the first switch because code==-1 and a broken response will be returned.

It should have instead continued the loop and have appended the string furthermore until it receives a valid response/code. So what I did for now was to change line 292:
``` if (fourthChar != '-') {```
to
``` if (code != -1 && fourthChar != '-') {```
and I also removed that -1 switch/case block. That works pretty fine so far. I'm just not sure about that access denied thingy. Perhaps you have an idea about that?

**Comment by hampelratte** [comment]
Ich denke, wir können hier auf deutsch wechseln, oder? Woher stammen die Daten denn ursprünglich? Sind das Daten, die von VDR aus dem DVB-Signal extrahiert wurden, oder kommen die von extern, z.B. EPG-Plugin oder ein Script? Laut manual page wird '|' als Zeilenumbruch interpretiert. Wenn der Text einen Zeilenumbruch enthält, müsste dieser also eigentlich durch '|' ersetzt worden sein.
Ich kann allerdings nicht sagen, ob das nur für \n gilt oder auch für \r und \r\n (also quasi alle drei gängigen Betriebssysteme).

**Comment by idl0r** [comment]
Hi,

die Daten kommen direkt vom VDR (LSTE), ich habe zwar einige Plugins installiert:
media-plugins/vdr-arghdirector
media-plugins/vdr-epgsearch
media-plugins/vdr-extrecmenu
media-plugins/vdr-femon
media-plugins/vdr-live
media-plugins/vdr-menuorg
media-plugins/vdr-sc
media-plugins/vdr-skinnopacity
media-plugins/vdr-skinpearlhd
media-plugins/vdr-softhddevice
media-plugins/vdr-text2skin
media-plugins/vdr-tvguide
media-plugins/vdr-xineliboutput

aber keines davon sollte (m.W.) solche Änderungen an den EPG Daten vornehmen. In meinem Fall ist DVB-C via Unitymedia im Einsatz - falls es damit zusammenhängt.
Zumindest in Connection.java sehe ich allerdings nichts was noch vor dem einlesen in "in" (BufferedReader) die Newlines ersetzt, oder meinst du von VDR selbst?

**Comment by hampelratte** [comment]
> oder meinst du von VDR selbst?

Ja genau. Wenn Du in die manual page schaust (man 5 vdr): "The first character of each line defines what kind of data this line contains." und "\<description\>       is the description of the event (any '|' characters will be interpreted as newlines)". Daraus schließe ich, dass die description komplett in eine Zeile gehört und Zeilenumbrüche müssen durch '|' ersetzt werden. Das gilt für die Kommunikation in beide Richtungen. In Deinem Fall dürfte also gar kein \r mehr in den Daten vorhanden sein, sondern stattdessen ein '|'. 

Ich frage mich auch, warum da einzelne carriage returns enthalten ist. Das wird ja sonst nur von Mac OS einzeln verwendet.

**Comment by idl0r** [comment]
Ich habe Klaus mal eine Mail inkl. Patch geschickt, mal schauen was er dazu meint.
0001-Replace-any-newline-charachter-in-EPG-descriptions.patch:
```
From 94a7b641032052ad0b22f3b7016a85b1638b1b15 Mon Sep 17 00:00:00 2001
From: Christian Ruppert <idl0r@gentoo.org>
Date: Mon, 28 Sep 2015 21:59:43 +0200
Subject: [PATCH] Replace any newline charachter in EPG descriptions

After having noticed some issues[1] with EPG descriptions it turned out that some
provider use common LF while some others also use CR and in case one uses both
I've extended the newline replacement for EPG descriptions to catch any (more or
less) common case:
First:  \r\n
Second: \r
Third:  \n

[1] https://github.com/hampelratte/svdrp4j/issues/2

Signed-off-by: Christian Ruppert <idl0r@gentoo.org>
---
 epg.c | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/epg.c b/epg.c
index 4297350..50c0c30 100644
--- a/epg.c
+++ b/epg.c
@@ -449,6 +449,8 @@ void cEvent::Dump(FILE *f, const char *Prefix, bool InfoOnly) const
      if (!isempty(shortText))
         fprintf(f, "%sS %s\n", Prefix, shortText);
      if (!isempty(description)) {
+        strreplace(description, "\r\n", "|");
+        strreplace(description, '\r', '|'); // Some EPG data contains CR only
         strreplace(description, '\n', '|');
         fprintf(f, "%sD %s\n", Prefix, description);
         strreplace(description, '|', '\n');
-- 
2.4.9
```

**Comment by idl0r** [comment]
Ich habe Klaus mal eine Mail inkl. Patch geschickt, mal schauen was er dazu meint.
0001-Replace-any-newline-charachter-in-EPG-descriptions.patch:
```
From 94a7b641032052ad0b22f3b7016a85b1638b1b15 Mon Sep 17 00:00:00 2001
From: Christian Ruppert <idl0r@gentoo.org>
Date: Mon, 28 Sep 2015 21:59:43 +0200
Subject: [PATCH] Replace any newline charachter in EPG descriptions

After having noticed some issues[1] with EPG descriptions it turned out that some
provider use common LF while some others also use CR and in case one uses both
I've extended the newline replacement for EPG descriptions to catch any (more or
less) common case:
First:  \r\n
Second: \r
Third:  \n

[1] https://github.com/hampelratte/svdrp4j/issues/2

Signed-off-by: Christian Ruppert <idl0r@gentoo.org>
---
 epg.c | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/epg.c b/epg.c
index 4297350..50c0c30 100644
--- a/epg.c
+++ b/epg.c
@@ -449,6 +449,8 @@ void cEvent::Dump(FILE *f, const char *Prefix, bool InfoOnly) const
      if (!isempty(shortText))
         fprintf(f, "%sS %s\n", Prefix, shortText);
      if (!isempty(description)) {
+        strreplace(description, "\r\n", "|");
+        strreplace(description, '\r', '|'); // Some EPG data contains CR only
         strreplace(description, '\n', '|');
         fprintf(f, "%sD %s\n", Prefix, description);
         strreplace(description, '|', '\n');
-- 
2.4.9
```

**Comment by idl0r** [comment]
In 2.3.1 ist das schon gefixt:
```
--- epg.c       2015/08/23 10:39:59     4.1
+++ epg.c       2015/09/10 10:58:19     4.2
@@ -7,7 +7,7 @@
  * Original version (as used in VDR before 1.3.0) written by
  * Robert Schneider <Robert.Schneider@web.de> and Rolf Hakenes <hakenes@hippomi.de>.
  *
- * $Id: epg.c 4.1 2015/08/23 10:39:59 kls Exp $
+ * $Id: epg.c 4.2 2015/09/10 10:58:19 kls Exp $
  */

 #include "epg.h"
@@ -661,7 +661,7 @@
            uchar *p = (uchar *)s;
            if (l == 2 && *p == 0xC2) // UTF-8 sequence
               p++;
-           if (*p == 0x86 || *p == 0x87) {
+           if (*p == 0x86 || *p == 0x87 || *p == 0x0D) {
               memmove(s, p + 1, len - l + 1); // we also copy the terminating 0!
               len -= l;
               l = 0;
```

Habs noch nicht ausprobiert aber das sieht richtig aus, daher schließe ich das Ticket mal. Danke!

**Comment by hampelratte** [comment]
Sehr gut. Tickets, die sich von selbst schließen, sind mir am liebsten ;)
