### ISSUE TITLE
svdrp4j can't handle marks for damaged recordings (new in vdr 2.5.6)

### ISSUE THREAD

**Issue by seahawk1986** [hampelratte/svdrp4j#7]
Hello,
vdr 2.5.6 introduces marking recordings with errors (the [error detection was introduced in vdr 2.5.4](http://git.tvdr.de/?p=vdr.git;a=blob;f=HISTORY;h=d57fb82d7f93bc5f1d00fe3a56b702a3ab580f9a;hb=HEAD#l9673)) with an additional `!`:
http://git.tvdr.de/?p=vdr.git;a=blobdiff;f=recording.c;h=47587de75b8beec063fb082fd7849c57fafbcac7;hp=f9ff14b11c5186f47538803b9b2a927f372ac904;hb=7301f2de0879fe10bf22c16191fcfd7bf836e148;hpb=8c7d387e8650d82883685602708fe05c6b655a8b
So the duration for a recording can be appended with up to two characters (`*` and `!` to signal a new resp. a damaged recording).

If https://github.com/hampelratte/svdrp4j/blob/f327f37598e5f93ac6047d6093c2307fe994ef51/src/main/java/org/hampelratte/svdrp/parsers/RecordingListParser.java#L126-L136 does not find an expected character the following code tries to parse the full string into an integer:
https://github.com/hampelratte/svdrp4j/blob/d210f2f0f36f012300f9576b901299aea02d7f16/src/main/java/org/hampelratte/svdrp/parsers/RecordingListParser.java#L87-L99  and because a `NumberFormatException` occuring in line 97 is not handled, an empty recording list is displayed by the lazybones plugin: https://www.vdr-portal.de/forum/index.php?thread/134580-vdr-developer-version-2-5-6/&postID=1342588#post1342588

**Comment by hampelratte** [comment]
Fixed in svdrp4j 1.2.0 and will be included in Lazy Bones 1.6.0
